### ISSUE TITLE
Close icon on popup misplaced and too big?

### ISSUE THREAD

**Issue by ComLock** [enonic/app-corporate-theme#1]
<img width="1156" alt="screen shot 2017-07-25 at 09 28 18" src="https://user-images.githubusercontent.com/118847/28560601-b526bde6-711b-11e7-8e24-428138b96459.png">

**Comment by Bellfalasch** [comment]
That was some work in progress I forgot. Nice pointing it out, thx!
![screen shot 2017-08-01 at 08 10 11](https://user-images.githubusercontent.com/1465598/28811648-e0eae702-7690-11e7-94ef-eaba2097a5c2.png)
