### ISSUE TITLE
Broken layout in image selectors

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-corporate-theme#27]
1. Install `Corporate Theme` , then  open  `My Corporation site`
2. Open Page Component View and insert an image-component
3. click on drop down handle 

BUG - broken layout in the selector:

![image](https://user-images.githubusercontent.com/3728712/57684874-56a23900-763f-11e9-96e3-307928301e68.png)

**Comment by alansemenov** [comment]
Fixed and released new version 2.1.0
