### ISSUE TITLE
Widget gear icon not visible for some users

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-corporate-theme#32]
During Content 101 last week some users, on both Mac OS and Windows, reported and demonstrated that they couldn't see the widget gear icon in the upper right. I don't know if this pertains to Enonic XP 7.0 only, to the Corporate Theme on 7.0 only, or more generally.

**Comment by alansemenov** [comment]
Couldn't reproduce. This cannot be related to the Corporate Theme app, so if you see this again during a course please let me know
