### ISSUE TITLE
Publishing issues with siblings and children

### ISSUE THREAD

**Issue by vot-enonic** [enonic/app-corporate-theme#33]
During Content 101 last week one participant experienced a bug where sibling contents were prompted to be published together with one particular content. Isn't this in violation with the content publishing hierarchy logic, where only children contents should be published?

Also: Not all underlying child contents in the Corporate Theme were prompted to be published together with parent content, according to some participants. Try to re-create this issue on Corporate Theme on Enonic XP 7.0.

**Comment by alansemenov** [comment]
@vot-enonic It's not only child items that are supposed to be published, actually child items are allowed to be excluded from publishing altogether. But dependencies are required for publishing. So this has to be considered for each specific case. If you are wondering why some item is required for publishing, check its incoming dependencies (via "Dependencies" widget) or come over and I'll explain
