### ISSUE TITLE
Article breaks on v2.3.0

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-corporate-theme#54]
Corporate theme 2.3.0 seems broken on XP 7.10.2.
Corporate theme 2.3.0 is also broken on XP 7.8.5.
Corporate theme 2.2.0 works on XP 7.7.4.

See attached screenshot for error messages. Tested on clean sandboxes.

<img width="1722" alt="Screenshot 2022-08-29 at 11 39 48" src="https://user-images.githubusercontent.com/5877868/187189672-b00d1524-3b79-483a-91a5-ba31b1786c73.png">

**Comment by reisfmb** [comment]
@jonaslepsoy 
Thanks for the bug report. It is fixed in the latest version: 2.3.1.
